version: '3.3'

services:
  mariadb:
    image: mariadb:latest
    environment:
      - MARIADB_DATABASE=my_db
      - MARIADB_USER=root
      - MARIADB_PASSWORD=123456
      - MARIADB_ROOT_USER
      - MARIADB_ROOT_PASSWORD=123456
    volumes:
      - ./mariadb_data:/var/lib/mariadb/data
    ports:
      - '3306:3306'
