version: '3.3'

services:
  mariadb:
    image: mariadb:latest
    environment:
      - MARIADB_DATABASE=my_db
      - MARIADB_ROOT_PASSWORD=admin123
    ports:
      - 3306:3306
    volumes:
      - ./mariadb_data:/var/lib/mariadb/data