version: '3.3'

services:
  mariadb:
    image: mariadb:latest
    environment:
      - MARIADB_DATABASE=my_db
      - MARIADB_ROOT_PASSWORD=admin123
    ports:
      - 3306:3306
    volumes:
      - ./mariadb_data:/var/lib/mariadb/data
  
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - mariadb